### ISSUE TITLE
Module for multi-channel images?

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#201]
We don't have yet any teaching module for multi-channel images.

I think I could just add this concept to the image file format module that I am working on.

The concept would be 

```
image file ---can contain---> multiple channels
```

...or do you feel we need a special module for the concept of multiple channels in one image?

We could make a module called multi-channel image visualisation...

Any opinions @manerotoni @AnniekStok ?

**Comment by AnniekStok** [comment]
Is there anything on hyperstacks in general? I am wondering if the channels concept could be part of that. I can imagine an activity where you have a linear stack that can be rearranged into different hyperstacks, illustrating the dimensionality of the data. But since this is possible with multiple file formats I would keep the two separate I guess.

**Comment by tischi** [comment]
"Hyperstacks" is an ImageJ term, which we cannot use for the module (only in the specific IJ activity). 

Maybe something like "Multi-dimensional image data handling"?

That could include:
- visualisation
- rearranging the dimensions 
- extracting subsets, e.g. only one time point

**Comment by AnniekStok** [comment]
I already thought you would say that :P but I wasn’t sure what the correct common word for hyperstack is. But ‘multidimensional image data handling’ sounds good to me and I think those topics you mentioned would be useful! I can also help creating such module, at least for the macro/jython part.

**Comment by manerotoni** [comment]
The module `image file format` reads more about what you can get from your instruments and how to save the data. 

I think if at all, I would suggest a module that covers anything anything that is more than 2D. XYZ, XYZC, XYZCT, XYZCTAngle, .... Anything that has multiple dimensions. So I would not restrict this to multiple channels. 

Depending on the software the handling of the data may be quite complicated.

**Comment by manerotoni** [comment]
For a multidimensional image we should also mention the index. We do this in 3D images, but in fact it applies for any dimensions. 
I think that mathematically speaking a multi-dimensional image is a tensor.

**Comment by tischi** [comment]
Coming back to this, I think I would like to add such a multi-channel rendering module.

One activity would be to open:

```
im_c0.tiff
im_c1.tiff
```

and then how to create a nice looking composite image with LUTs a.s.o.

@manerotoni @AnniekStok what do you think?

**Comment by manerotoni** [comment]
Hi Tischi,
yes it is a good idea. 

I was reading back the comments. 
One can also have a generic multi stack image split in single (img_C0_Z001_T001.tiff, ...) images where you want to load it back and visualise. This is kind of the generic case. In imageJ you have to define the Hyperstack, in python you have to construct your multi-dimensional array.

**Comment by tischi** [comment]
@manerotoni thank you for your input. 

Conceptually the issue is a little bit what the scope of this module should be: https://neubias.github.io/training-resources/multidimensional_image_basics/index.html 
... in comparison to the multi-channel image module.

Personally I feel having a dedicated multi-channel image module makes sense, because there are specific issues like how to render the different colours on top of each other, which I don't think we should discuss in a generic ND image module.

**Comment by AnniekStok** [comment]
First opening individual channels separately and showing how you can view them as a composite image would be nice to demonstrate the concept. 

In napari, I think the multichannel image loading is something that confuses people sometimes. Depending on the file and on the reader you are using, napari may open a multichannel image as a ND array or it may split the different channels and show them as separate layers. If it gives you a single multidimensional array you need to get the channels out as separate layers yourself if you want to see a composite image. So maybe the ND image module (or a 'rearranging ND images module' can follow up on the multi-channel module since users may have to deal with this kind of problem if they try to load a multichannel image directly.

**Comment by tischi** [comment]
We now have such a module.
