### ISSUE TITLE
Improve image calibration and pixels figure

### ISSUE THREAD

**Issue by tischi** [NEUBIAS/training-resources#220]
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/2157566/149886971-7dc60a61-04fb-4f78-9ef3-be1ed293646e.png">

I think it would be good to add something that shows that a pixel in the image has both indices and real world coordinates.

**Comment by manerotoni** [comment]
What about an extra rectangle, before the area rectangle,  where you show the index and the real coordinate on top of each other.
This is kind of the position of the middle of the pixel.
index =0 , x =0
index =1, x. = dx
index = 2, x = 2*dx .
It gets a bit confusing with the area. With the area you do not think of coordinates but of widths.

**Comment by tischi** [comment]
What about adding a zoom-in to the example image on the left where the individual pixels are visible.
And then for one of the pixels we show both the indices and the coordinates?

Also, I think we should switch, first the drawings and then the example image.

**Comment by manerotoni** [comment]
Sounds good

**Comment by tischi** [comment]
Ok, then I will do it today.

**Comment by VolkerH** [comment]
While I casually also talk of pixel/voxel width, height and depth, I think this can be misleading.

I think what you are referring to here is really pixel spacing in the object space, i.e. what is the distance between two adjacent intensity samples.

By calling them width and height, there is potential to confuse these with resolution and also potential to confuse them with the actual width and height of the sensor elements on the camera chip (where spacing and actual size are also different)

**Comment by VolkerH** [comment]
See also [A pixel is not a little square](http://alvyray.com/Memos/CG/Microsoft/6_pixel.pdf)

**Comment by manerotoni** [comment]
@VolkerH 
Very good point. I have to say that the terminology is also used in IJ. Spacing may be the more correct description. 
Physically, the information of a pixel is the number of photons reaching a detection element of size pixel_width*pixel_height. 
For a LSM it is a little bit more complicated as it is the number of photons coming from an excitation of pixel_width.

**Comment by VolkerH** [comment]
> Physically, the value of a pixel is the number of photons reaching a detection element of size pixel_width*pixel_height during a certain time.

IMHO, that is still too specific. The value of a pixel is simply a measurement sampled at a point. Can be photons, can be electrons or grains of sand if you manually count something during field work. 
The detection element is separate. In a laser-scanning confocal you can have a PMT tube and usually one would not specify the size of the PMT tube as detection element. But clearly, you have an image made of pixels in a laser-scanning confocal.

**Comment by tischi** [comment]
Thanks @VolkerH, in fact I also agree! 
I wonder whether we are getting the whole concept wrong...
Maybe we should rather start from "An image is a mapping from R^N to R" or something like this...

@VolkerH if you would have to draw a conceptual figure to explain pixels, indices and real world coordinates, what would you draw? Maybe we should be more clear that pixels are just a particular way to store the data?

**Comment by VolkerH** [comment]
I might want to phrase it like this:
A raster image of some real-world thing is a collection of spatially sampled measuments. So basically a list of positions and corresponding measuerments. If you go and measure ground water level every 100 meters in East-West and Noth-South direction, you can build an image. Your spatial calibration would be 100 m per pixel (ugh) even if you sample in a much smaller hole.

Some of the problem comes from the multiple meanings of the word pixels in different contexts, e.g. referring to sensels etc.
The wikipedia page is actually quite good:
https://en.wikipedia.org/wiki/Pixel

I particularly like the different renderings (e.g. small dots, lines, smooth) which help.

What would I draw? I don't know. But maybe the image of someone going around a field measuring water levels at certain positions is a useful abstraction that goes away from camera pixels but still makes it very clear how you can build an image. It is also quite easy to explain that there can be different sampling patterns (regular: square, hexagonal , random) in that context.

**Comment by VolkerH** [comment]
Just to add: for the specific spatial calibration explanation here, I think  it is sufficient to just talk of the spacing of the pixels in the world space.

The finer points could be a separate module on image formation. There one could discuss sampling and also the need for low-pass filtering prior to sampling etc.

**Comment by tischi** [comment]
> Just to add: for the specific spatial calibration explanation here, I think it is sufficient to just talk of the spacing of the pixels in the world space.

I don't have time to integrate all the very good points you made (I have to teach this tomorrow).
Could you suggest some "quick fixes" to the current figure?

<img width="724" alt="image" src="https://user-images.githubusercontent.com/2157566/149945184-98a336ea-b85b-48d9-a06e-65763cc6d108.png">

Maybe we should draw several "pixels" (how? maybe just dots instead of squares?) and rather speaking about "spacing of the centers" rather than "width" and "height"?

**Comment by VolkerH** [comment]
For a quick change, I would replace the top-left square with 4 points and change the text labels to
*horizontal pixel spacing `dx`* and *vertical pixel spacing `dy`*

For the area diagram , maybe put some dots in the center of the squares? 

Regarding the image on the right: location is a bit unclear without a defined origin of the coordinate system. In this case it is um from the top-left of the image? Could be relative to some stage coordinate (needs to be otherwise known, e.g. metadata and also need to know where that stage coordinate is anchored in the image, e.g. centre or top-left). 

Sorry, I don't have better suggestions of the cuff. Easy to point out the shortcomings but not trivial/quick to come up with something better.

**Comment by tischi** [comment]
Thanks @VolkerH 

I tried now like this:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/2157566/149959380-205b06a2-3f7a-427a-ae41-617f4c9545d2.png">

**Comment by VolkerH** [comment]
Not perfect, but definitely better IMO.

**Comment by manerotoni** [comment]
> I might want to phrase it like this: A raster image of some real-world thing is a collection of spatially sampled measuments. So basically a list of positions and corresponding measuerments. If you go and measure ground water level every 100 meters in East-West and Noth-South direction, you can build an image. Your spatial calibration would be 100 m per pixel (ugh) even if you sample in a much smaller hole.

We do not sample every 100 m. We scan continuously for 100 m and average the results. This is an LSM. The scanner does not jump, it is a linear scanner.
This is even more true for a camera.

**Comment by VolkerH** [comment]
Good point @manerotoni, regarding the linear scanning. 
I think one way to describe this is that there are both aggregation and sampling steps.

**Comment by tischi** [comment]
Pixels.... what a rabbit hole :-)

**Comment by tischi** [comment]
In fact, while we are at it, we should also improve this one:
https://neubias.github.io/training-resources/pixels/index.html
I think we should add some pixel _indices_ to the figure, right now one only sees the values.
