### ISSUE TITLE
Old ImageJ macro (from before 2010) does not work on recent ImageJ/Fiji versions (2022)

### ISSUE THREAD

**Issue by 5kup** [NEUBIAS/training-resources#283]
Hello,
I am a noob at programing, sorry about that!
I have an old macro (that I didn't write) that used to run flawlessly on imageJ back in the 2010 years (see attached, and in my gists).

https://gist.github.com/5kup/5f7991c681976dc2324b2c61426581ec
[MeasureSlabs_4SS.txt](https://github.com/NEUBIAS/training-resources/files/8049197/MeasureSlabs_4SS.txt)

I have tried to run it on a version of ImageJ available today, and also on Fiji, using the command 'Run Macro', and also just opening the *.txt file itself, but nothing is happening.
I have tried installing is as a plugin (as it is supposed to make new command buttons appear), there again no success.
I also tried to convert it to a java file with ImageJ, but the resulting java file is not usable.

Then I tried to retrieve older versions of ImageJ, but the oldest version I could try (2014) does not show any different behavior.

I also can't find any macro that is equivalent.

I would appreciate if somebody can help me!

Best regards,
5kup.

**Comment by manerotoni** [comment]
Hello @5kup ,
I think this repository is not the correct place for your question. This repository collects teaching material (also for ImageJ macro), but we do not debug macro code.  

Since 2010 many things have changed and you can try to file your question in https://forum.image.sc, ask the person that developed the imageJ plugin, or describe what you want to do and there may well be a plugin that does the same job but is up to date.
