### ISSUE TITLE
Filter object or filter labels

### ISSUE THREAD

**Issue by manerotoni** [NEUBIAS/training-resources#64]
We talk about objects but correctly we are filtering labels. Or 
Filter objects/labels ?

**Comment by tischi** [comment]
@manerotoni 

Good point! 

I am never sure what to say: 
- label
- image segment
- segment
- object
- particle
- instance

We should teach somewhere that those are all the same.

I think for the module titles maybe "Object"? 
As in "Object Intensity Measurements"?

I think "Label" is maybe not so good because one could represent an Object also by a Polygon ROI.

**Comment by manerotoni** [comment]
We keep object filtering
